# Cursor Bridge 本地tmux配置
# 用户手动管理连接，cursor-bridge只连接本地tmux会话

# 服务器配置
servers:
  # 本地tmux会话 - 主要工作环境
  local-tmux:
    type: "local_tmux"
    tmux:
      session_name: "dev"
      window_name: "main"
    session:
      name: "local-dev-session"
      working_directory: "/Users/xuyehua"
      environment:
        TERM: "xterm-256color"
        LANG: "en_US.UTF-8"
      shell: "/bin/zsh"

  # 百度服务器tmux会话
  baidu-tmux:
    type: "local_tmux"
    tmux:
      session_name: "baidu"
      window_name: "server"
    session:
      name: "baidu-dev-session"
      working_directory: "/Users/xuyehua"
      environment:
        TERM: "xterm-256color"
        LANG: "en_US.UTF-8"
      shell: "/bin/zsh"

# 默认服务器
default_server: "baidu-tmux"

# MCP服务器配置
mcp:
  server:
    host: "localhost"
    port: 8080
    log_level: "INFO"
    max_connections: 100
    
  features:
    command_history: true
    session_persistence: true
    auto_reconnect: true
    health_check_interval: 30
    command_timeout: 300
    prompts: false
    
  tools:
    - "execute_command"
    - "list_sessions"
    - "create_session"
    - "get_session_status"
    
  resources: []

# 安全配置
security:
  allowed_commands:
    - "ls"
    - "pwd"
    - "cd"
    - "cat"
    - "grep"
    - "find"
    - "git"
    - "python"
    - "python3"
    - "node"
    - "npm"
    - "pip"
    - "make"
    - "docker"
    - "kubectl"
    - "tmux"
  
  blocked_commands:
    - "rm -rf /"
    - "sudo rm"
    - "mkfs"
    
  blocked_patterns: []
  
  command_timeout: 300
  max_output_size: 10485760
  max_concurrent_commands: 10
  
  allowed_paths: []
  blocked_paths: []

# 监控配置
monitoring:
  metrics: {}
  health_check: {}
  logging:
    level: "INFO"
    format: "json"
    console: true

# 性能配置
performance:
  connection_pool: {}
  session_pool: {}
  command_execution: {}
  caching: {}