# Cursor Bridge 配置文件
# 这是一个示例配置，请根据实际环境进行调整

# 服务器配置
servers:
  # 通过企业VPN工具连接的内网服务器
  enterprise-dev:
    type: proxy
    proxy:
      command: enterprise-vpn-tool
      target_host: internal-server.company.com
      target_port: 22
      username: your-username
      timeout: 30
      # 可选：VPN工具的额外参数
      extra_args: []
    session:
      name: enterprise-dev-session
      working_directory: /home/Code
      environment:
        TERM: xterm-256color
        LANG: en_US.UTF-8
      shell: /bin/bash
      
  # 直接SSH连接的服务器示例
  # direct-server:
  #   type: direct
  #   ssh:
  #     host: your-server.com
  #     port: 22
  #     username: your-username
  #     key_file: ~/.ssh/id_rsa
  #     timeout: 10
  #   session:
  #     name: direct-session
  #     working_directory: /home/user

# MCP服务器配置
mcp:
  server:
    host: localhost
    port: 8082
    log_level: INFO
    max_connections: 100
    
  features:
    command_history: true
    session_persistence: true
    auto_reconnect: true
    health_check_interval: 30
    command_timeout: 300
    
  tools:
    - execute_command
    - get_session_status
    - create_session
    - destroy_session
    - list_sessions
    
  resources:
    - session_logs
    - command_history
    - server_status

# 安全配置
security:
  # 命令白名单（为空表示允许所有命令）
  allowed_commands: []
  
  # 命令黑名单
  blocked_commands:
    - "rm -rf /"
    - "sudo rm"
    - "mkfs"
    - "dd if="
    - ":(){ :|:& };:"
    
  # 命令模式过滤
  blocked_patterns:
    - "rm.*-rf.*/"
    - "sudo.*rm"
    - "chmod.*777"
    
  # 执行限制
  command_timeout: 300
  max_output_size: 10485760  # 10MB
  max_concurrent_commands: 10
  
  # 文件访问限制
  allowed_paths:
    - "/home"
    - "/tmp"
    - "/var/log"
    
  blocked_paths:
    - "/etc/passwd"
    - "/etc/shadow"
    - "/root"

# 监控配置
monitoring:
  metrics:
    enabled: true
    port: 9090
    path: /metrics
    
  health_check:
    enabled: true
    port: 8083
    path: /health
    
  logging:
    level: INFO
    format: json
    file: /var/log/cursor-bridge.log
    max_size: 100MB
    backup_count: 5

# 性能配置
performance:
  connection_pool:
    max_size: 20
    min_size: 2
    max_idle_time: 300
    
  session_pool:
    max_sessions_per_server: 10
    session_idle_timeout: 600
    
  command_execution:
    default_timeout: 30
    max_timeout: 300
    buffer_size: 8192
    
  caching:
    command_history_size: 1000
    session_cache_ttl: 3600